//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlLabel.Forms.Plugin.Tests.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlSources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HtmlLabel.Forms.Plugin.Tests.App.HtmlSources", typeof(HtmlSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An align center string..
        /// </summary>
        public static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An align end string..
        /// </summary>
        public static string AlignEnd {
            get {
                return ResourceManager.GetString("AlignEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلسلة عربية..
        /// </summary>
        public static string Arab {
            get {
                return ResourceManager.GetString("Arab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;strong&gt;bold&lt;/strong&gt; string..
        /// </summary>
        public static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red color string.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tortor massa, fringilla ornare congue id, maximus eleifend justo. Donec ipsum nulla, hendrerit ut scelerisque nec, pellentesque in lorem.&lt;/p&gt;&lt;ol&gt;&lt;li&gt;test 1&lt;/li&gt;&lt;li&gt;Test 2&lt;ol&gt;&lt;li&gt;Test 2.1&lt;/li&gt;&lt;li&gt;test 2.2&lt;/li&gt;&lt;/ol&gt;&lt;/li&gt;&lt;/ol&gt;&lt;p&gt;Donec pharetra quam mi, ac mollis lacus ultrices vitae. Aenean vitae suscipit felis. Donec convallis orci vitae magna consectetur, lobortis vulputate lectus ultrices.&lt;/p&gt;&lt;p&gt;Maecenas fermentum leo non augue sagittis consecte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &lt;em&gt;italic&lt;/em&gt; string..
        /// </summary>
        public static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt;..
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with options..
        /// </summary>
        public static string LinksWithOptions {
            get {
                return ResourceManager.GetString("LinksWithOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to &lt;a href=&quot;mailto:github@github.com?subject=Awesome&amp;body=Awesome%20plugin&quot;&gt;github@github.com&lt;/a&gt;..
        /// </summary>
        public static string LinkToEmail {
            get {
                return ResourceManager.GetString("LinkToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS to &lt;a href=&quot;sms://8372717112?body=Awesome%20plugin&quot;&gt;8372717112&lt;/a&gt;..
        /// </summary>
        public static string LinkToSms {
            get {
                return ResourceManager.GetString("LinkToSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &lt;a href=&quot;tel://8372717112&quot;&gt;8372717112&lt;/a&gt;..
        /// </summary>
        public static string LinkToTel {
            get {
                return ResourceManager.GetString("LinkToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with custom color..
        /// </summary>
        public static string LinkWithColor {
            get {
                return ResourceManager.GetString("LinkWithColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A label with custom gestures..
        /// </summary>
        public static string LinkWithGestures {
            get {
                return ResourceManager.GetString("LinkWithGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with no underline..
        /// </summary>
        public static string LinkWithoutUnderline {
            get {
                return ResourceManager.GetString("LinkWithoutUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ol&gt;&lt;li&gt;Test&lt;/li&gt;&lt;li&gt;Test 2&lt;/li&gt;&lt;/ol&gt;&lt;ul&gt;&lt;li&gt;Test 1&lt;/li&gt;&lt;li&gt;Test 2&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tortor massa, fringilla ornare congue id, maximus eleifend justo. Donec ipsum nulla, hendrerit ut scelerisque nec, pellentesque in lorem.&lt;/p&gt;&lt;p&gt;Donec pharetra quam mi, ac mollis lacus ultrices vitae. Aenean vitae suscipit felis. Donec convallis orci vitae magna consectetur, lobortis vulputate lectus ultrices.&lt;/p&gt;&lt;p&gt;Maecenas fermentum leo non augue sagittis consectetur. Quisque feugiat a magna sit amet tempus. Morbi ac ornare nibh, in viverra dui [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
    }
}
