//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtmlLabel.Forms.Plugin.Tests.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlSources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HtmlLabel.Forms.Plugin.Tests.App.HtmlSources", typeof(HtmlSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An align center string..
        /// </summary>
        internal static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An align end string..
        /// </summary>
        internal static string AlignEnd {
            get {
                return ResourceManager.GetString("AlignEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلسلة عربية..
        /// </summary>
        internal static string Arab {
            get {
                return ResourceManager.GetString("Arab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &lt;strong&gt;bold&lt;/strong&gt; string..
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red color string..
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a string with a custom font..
        /// </summary>
        internal static string CustomFont {
            get {
                return ResourceManager.GetString("CustomFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text with image &lt;img src=&quot;https://raw.githubusercontent.com/matteobortolazzo/HtmlLabelPlugin/master/Assets/icon.png&quot; /&gt;.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An &lt;em&gt;italic&lt;/em&gt; string..
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a string with a different line height..
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt;..
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with Internal Webview..
        /// </summary>
        internal static string LinksWithInternalWebView {
            get {
                return ResourceManager.GetString("LinksWithInternalWebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with options..
        /// </summary>
        internal static string LinksWithOptions {
            get {
                return ResourceManager.GetString("LinksWithOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to &lt;a href=&quot;mailto:github@github.com?subject=Awesome&amp;body=Awesome%20plugin&quot;&gt;github@github.com&lt;/a&gt;..
        /// </summary>
        internal static string LinkToEmail {
            get {
                return ResourceManager.GetString("LinkToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to open maps &lt;a href=&quot;geo:53.3242377,-6.3861295;u=5&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string LinkToGeo {
            get {
                return ResourceManager.GetString("LinkToGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS to &lt;a href=&quot;sms://8372717112?body=Awesome%20plugin&quot;&gt;8372717112&lt;/a&gt;..
        /// </summary>
        internal static string LinkToSms {
            get {
                return ResourceManager.GetString("LinkToSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &lt;a href=&quot;tel://8372717112&quot;&gt;8372717112&lt;/a&gt;..
        /// </summary>
        internal static string LinkToTel {
            get {
                return ResourceManager.GetString("LinkToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call to &lt;a href=&quot;tel:083 7271 7112&quot;&gt;08372717112&lt;/a&gt;..
        /// </summary>
        internal static string LinkToTelAlternate {
            get {
                return ResourceManager.GetString("LinkToTelAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with custom color..
        /// </summary>
        internal static string LinkWithColor {
            get {
                return ResourceManager.GetString("LinkWithColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A label with custom gestures..
        /// </summary>
        internal static string LinkWithGestures {
            get {
                return ResourceManager.GetString("LinkWithGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a &lt;a href=&quot;https://github.com/matteobortolazzo/HtmlLabelPlugin&quot;&gt;Link&lt;/a&gt; with no underline..
        /// </summary>
        internal static string LinkWithoutUnderline {
            get {
                return ResourceManager.GetString("LinkWithoutUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List&lt;ul&gt;&lt;li&gt;First item&lt;/li&gt;&lt;li&gt;Second item&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;First paragraph&lt;/p&gt;&lt;p&gt;Second paragraph&lt;/p&gt;.
        /// </summary>
        internal static string Paragraphs {
            get {
                return ResourceManager.GetString("Paragraphs", resourceCulture);
            }
        }
    }
}
